§FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# monocle

API для получения радиолокационных данных. Все комментарии на русском, в соответствии со спецификацией. В именах сущностей часть названий, для которых удалось подобрать соотвествующий англоязычный аналог, передена на английский, часть оставлена в виде аббревиатур, соответсвующих русскоязычным аббревиатурам.

## АС СМРЛП [/station/list{?ids}{?title}{?limit}{?offset}]

Запрос состава АС СМРЛП и параметров отдельных постов

### Получить список СМРЛП [GET]

+ Parameters
    * ids - Фильтр по id
    + title - Фильтр по названию
    + limit - Количество строк на странице
    + offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 5,
            "items": [
                {
                    "id": 0,
                    "index": "0001",
                    "title": "Орловка",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "terrain_altitude": 0,
                    "radar_elevation": 0,
                    "pressure_sensor_elevation": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e3",
                        "title": "Обзор 50 км УМ 0-90°",
                        "timetable_enabled": true
                    },
                    "alarm_id": 0,
                    "local_reflections_status": "Построена 28.03.2018 в 09:54:32",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 1,
                    "index": "0002",
                    "title": "Чкаловский",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "terrain_altitude": 0,
                    "radar_elevation": 0,
                    "pressure_sensor_elevation": 0,
                    "terrain_type": "coldsea",
                    "current_program": {
                        "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e1",
                        "title": "Обзор 50 км УМ 0-90°",
                        "timetable_enabled": false
                    },
                    "alarm_id": 0,
                    "local_reflections_status": "Идёт построение (9 из 10)",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 2,
                    "index": "0003",
                    "title": "Елец",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "terrain_altitude": 0,
                    "radar_elevation": 0,
                    "pressure_sensor_elevation": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e4",
                        "title": "Готовность",
                        "timetable_enabled": false
                    },
                    "alarm_id": 0,
                    "local_reflections_status": "Идёт построение (Завершено циклов: 3 из 20)",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 3,
                    "index": "0004",
                    "title": "Тула",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "terrain_altitude": 0,
                    "radar_elevation": 1,
                    "pressure_sensor_elevation": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e8",
                        "title": "Готовность",
                        "timetable_enabled": true
                    },
                    "alarm_id": 0,
                    "local_reflections_status": "Нет данных",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 4,
                    "index": "0005",
                    "title": "Щелково",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "terrain_altitude": 0,
                    "radar_elevation": 1,
                    "pressure_sensor_elevation": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e9",
                        "title": "Готовность",
                        "timetable_enabled": false
                    },
                    "alarm_id": 0,
                    "local_reflections_status": "Отсутствует",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                }
            ]
        }

## СМРЛП [/station/{id}]

Параметры отдельного СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить параметры СМРЛП [GET]

+ Response 200 (application/json)

            {
                "id": 3,
                "index": "0003",
                "title": "Елец",
                "latitude": 55.807775,
                "longitude": 37.566814,
                "terrain_altitude": 0,
                "radar_elevation": 0,
                "pressure_sensor_elevation": 0,
                "terrain_type": "land",
                "current_program": {
                    "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e3",
                    "title": "Готовность",
                    "timetable_enabled": true
                },
                "alarm_id": 0,
                "local_reflections_status": "Идёт построение (Завершено циклов: 3 из 20)",
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
            
+ Response 404

### Обновить параметры СМРЛП [PUT]

+ Request (application/json)

        {
            "index": "0003",
            "title": "Елец",
            "latitude": 55.807775,
            "longitude": 37.566814,
            "terrain_altitude": 0,
            "radar_elevation": 0,
            "pressure_sensor_elevation": 0,
            "terrain_type": "land",
            "alarm_id": 0
        }

+ Response 422 (application/json)

    + Body

            {
                "index": "Индекс не уникален",
                "title": "Невалидное значение",
                "terrainType": "Невалидное значение",
                "latitude": "Невалидное значение",
                "longitude": "Невалидное значение",
                "terrain_altitude": "Невалидное значение",
                "radar_elevation": "Невалидное значение",
                "pressure_sensor_elevation": "Невалидное значение",
                "alarm_id": "Невалидное значение"
            }

+ Response 200 (application/json)

    + Body

            {
                "index": "0003",
                "title": "Елец",
                "latitude": 55.807775,
                "longitude": 37.566814,
                "terrain_altitude": 0,
                "radar_elevation": 0,
                "pressure_sensor_elevation": 0,
                "terrain_type": "land",
                "current_program": {
                    "id": "6d697530-25f1-11e8-a0e9-1c1b0d7db1e3",
                    "title": "Готовность",
                    "timetable_enabled": true
                },
                "alarm_id": 0,
                "local_reflections_status": "Идёт построение (Завершено циклов: 3 из 20)",
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
        
+ Response 404

## Справочник типов РЛП [/station/{id}/types/rlp_list]

Cправочник типов РЛП для СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить перечень типов РЛП [GET]

+ Response 200 (application/json)

        {
            "count": 12,
            "items": [{
                    "id": 0,
                    "index": "Wpcell",
                    "title": "Карта метео явлений (в ячейках)",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 1,
                    "index": "Wpfig",
                    "title": "Карта метео явлений (в контурах)",
                    "enable_altitude_scale": true,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 2,
                    "index": "Htmax",
                    "title": "Карта верхней границы радиоэха",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 3,
                    "index": "Htmin",
                    "title": "Карта нижней границы радиоэха",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 4,
                    "index": "VvField",
                    "title": "Карта векторного поля скоростей",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 5,
                    "index": "WindShiftH",
                    "title": "Объемная карта значений горизонтального сдвига ветра",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 6,
                    "index": "WindShiftV",
                    "title": "Объемная карта значений вертикального сдвига ветра",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 7,
                    "index": "VIL",
                    "title": "Карта интегрированного водозапаса в ячейках, кг/м^2",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 8,
                    "index": "RflS3",
                    "title": "Количество осадков накопленное за 3, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 9,
                    "index": "RflS6",
                    "title": "Количество осадков накопленное за 6, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 10,
                    "index": "RflS12",
                    "title": "Количество осадков накопленное за 12, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 11,
                    "index": "RflS24",
                    "title": "Количество осадков накопленное за 24, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                }
            ]
        }

## Справочник типов КС [/station/{id}/types/cs_list]

Cправочник типов конических сечений для СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить перечень типов КС [GET]

+ Response 200 (application/json)

        {
            "count": 5,
            "items": [{
                    "id": 12,
                    "index": "Dbz",
                    "title": "Отражаемость"
                },
                {
                    "id": 13,
                    "index": "Vr",
                    "title": "Радиальная скорость"
                },
                {
                    "id": 14,
                    "index": "Edr",
                    "title": "Уд. скорость диссипации турбулентной энергии"
                },
                {
                    "id": 15,
                    "index": "RflI",
                    "title": "интенсивность осадков"
                },
                {
                    "id": 16,
                    "index": "Power",
                    "title": "Мощность"
                }
            ]
        }

## Калибровка изотермы [/station/{id}/isotherm]

Настройка изотермы (0, -22 градуса), высоты тропопаузы,
переключение автоматического/ручного режима задания, ввод параметров вычисления.

+ Parameters
    + id (number) - ID СМРЛП

### Получить настройки вычисления изотермы [GET]

+ Response 200 (application/json)

        {
            "_comment_manual": "Задаётся ли высота нулевой изотермы вручную. Если false - вычисляется из данных НАМС",
            "manual": false,
            "_comment_expire_period": "Время истечения заданного вручную значения, ч",
            "expire_period": 12,
            "_comment_update_time": "Время последнего обновления",
            "update_time": "2017-05-15T08:30:00",
            "_comment_height_temp0": "Высота нулевой изотермы, задаваемая вручную",
            "height_temp0": 2400,
            "_comment_height_temp22": "Высота изотермы -22 градуса, задаваемая вручную",
            "height_temp22": 7000,
            "_comment_height_tropopause": "Высота тропопаузы, задаваемая вручную",
            "height_tropopause": 12000
        }
        
+ Response 404

### Обновить настройки вычисления изотермы [PUT]

+ Request (application/json)

        {
            "manual": false,
            "expire_period": 12,
            "_comment_manual_from_temp": "true: задаётся температура на уровне земли, false: задаётся высота нулевой изотермы",
            "manual_from_temp": false,
            "_comment_temperature": "Температура на уровне земли, задаваемая вручную",
            "temperature": 15.2,
            "height_temp0": 2400,
            "height_temp22": 7000,
            "height_tropopause": 12000
        }

+ Response 200 (application/json)

        {
            "manual": false,
            "expire_period": 12,
            "update_time": "2017-05-15T08:30:00",
            "height_temp0": 2400,
            "height_temp22": 7000,
            "height_tropopause": 12000
        }
        
+ Response 422 (application/json)

        {
            "temperature": "Невалидное значение",
        }
        
+ Response 404

+ Response 409

## Настройки критериев МЯ для отдельного СМРЛП [/station/{id}/meteosettings]

Настройки критериев метеоявлений для отдельного СМРЛП. Эти
настройки переопределяют значения общих настроек, задаваемых
в запросе "Критерии классификации типов метеоявлений по умолчанию"

+ Parameters
    + id (number) - ID СМРЛП

### Получить [GET]

+ Response 200 (application/json)

        {
            "_comment_min_dangerous_meteo": "Индекс минимального опасного МЯ",
            "min_dangerous_meteo": 5,
            "_comment_cloud_velocity_radial": "Скорость перемещения облачных масс: true - по радиальной скорости, false - по центру масс МЯ",
            "cloud_velocity_radial": true,
            "_comment_meteo_classes": "Настройки критериев метеоявлений",
            "meteo_classes":
            {
                "count": 2,
                "items":
                [
                    {
                        "index": 0,
                        "_comment_id": "Идентификатор МЯ. 0 означает отсутствие МЯ",
                        "id": 1, 
                        "type": "Слоистая облачность",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_bH_min",
                                    "title": "Пороговое значение HНГ для облачности верхнего и среднего ярусов",
                                    "measurement_unit": " м",
                                    "warm": 3000,
                                    "cold": 3000
                                }
                            ]
                        }
                    },
                    {
                        "id": 2, 
                        "type": "Облачность (кучевая облачность)",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                }
                            ]
                        }
                    },
                    {
                        "id": 5,
                        "type": "Осадки умеренные",
                        "criteria": {
                            "count": 1,
                            "items": [
                                {
                                    "code": "Rf_dBZ1",
                                    "title": "Пороговое значение отражаемости Z1",
                                    "measurement_unit": " dBZ",
                                    "warm": 20,
                                    "cold": 19,
                                    "index": 0
                                }
                            ]
                        },
                        "index": 4
                    }
                ]
            }
        }
            
+ Response 404

### Обновить настройки СМРЛП [PUT]

+ Request (application/json)

        {
            "min_dangerous_meteo": 5,
            "cloud_velocity_radial": true,
            "meteo_classes":
            {
                "count": 2,
                "items":
                [
                    {
                        "index": 0,
                        "id": 2, 
                        "type": "Слоистая облачность",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_bH_min",
                                    "title": "Пороговое значение HНГ для облачности верхнего и среднего ярусов",
                                    "measurement_unit": " м",
                                    "warm": 3000,
                                    "cold": 3000
                                }
                            ]
                        }
                    },
                    {
                        "id": 2, 
                        "type": "Облачность (кучевая облачность)",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                }
                            ]
                        }
                    }
                ]
            }
        }

+ Response 422

        {
            "meteo_classes":
            {
                "count": 1,
                "items":
                [
                    {
                        "index": 0,
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "cold": "Невалидное значение"
                                }
                            ]
                        }
                    }
                ]
            }
        }

+ Response 200 (application/json)

        {
            "min_dangerous_meteo": 5,
            "cloud_velocity_radial": true,
            "meteo_classes":
            {
                "count": 2,
                "items":
                [
                    {
                        "index": 0,
                        "id": 2, 
                        "type": "Слоистая облачность",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_bH_min",
                                    "title": "Пороговое значение HНГ для облачности верхнего и среднего ярусов",
                                    "measurement_unit": " м",
                                    "warm": 3000,
                                    "cold": 3000
                                }
                            ]
                        }
                    },
                    {
                        "id": 2, 
                        "type": "Облачность (кучевая облачность)",
                        "criteria":
                        {
                            "count": 1,
                            "items":
                            [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement_unit": "dBZ",
                                    "warm": 35,
                                    "cold": 30
                                }
                            ]
                        }
                    }
                ]
            }
        }
            
+ Response 409

+ Response 404

## Настройки МРЛС [/station/{id}/radarsettings]

Настройки МРЛС на выбранном СМРЛП. Запрос может выполняться только если
РЛС находится в режиме ГОТОВНОСТЬ. Режим можно узнать из текущего статуса.
При попытке запросить настройки в режиме, отличном от ГОТОВНОСТи, возвращается 409
При указании невалидного id СМРЛП, возвращается 404

+ Parameters
    + id (number) - ID СМРЛП

### Получить настройки МРЛС [GET]

+ Response 200 (application/json)

            {
                "_comment_channel_id": "Номер канала излучения МРЛС",
                "channel_id": 2,
                "_comment_hold_azimuth": "Фиксированный азимут антенны, град.",
                "hold_azimuth": 60.0,
                "_comment_hold_tilt": "Фиксированный угол места антенны, град.",
                "hold_tilt": 16.0,
                "_comment_azimuth_center": "Поправка на север",
                "azimuth_center": 0.0
            }
            
### Обновить настройки МРЛС [PUT]

+ Request (application/json)

            {
                "channel_id": 2,
                "hold_azimuth": 60.0,
                "hold_tilt": 16.0,
                "azimuth_center": 0.0
            }

+ Response 200 (application/json)

            {
                "channel_id": 2,
                "hold_azimuth": 60.0,
                "hold_tilt": 16.0,
                "azimuth_center": 0.0
            }
            
+ Response 422

        {
                "channel_id": "Невалидное значение",
                "hold_azimuth": "Невалидное значение",
                "hold_tilt": "Невалидное значение",
                "azimuth_center": "Невалидное значение"
        }
            
+ Response 409

+ Response 404

## Расписание СМРЛП [/station/{id}/schedule]

Работа с расписанием работы отдельного СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить расписание СМРЛП [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
            [
                {
                    "id": 0,
                    "program_id": "b8e8bf60-25d9-11e8-a0e9-1c1b0d7db1e3",
                    "date": "17:30:46"
                },
                {
                    "id": 1,
                    "program_id": "b8e8bf60-25d9-21e8-a0e9-1c1b0d7db1e3",
                    "date": "17:50:46"
                }
            ]
        }
+ Response 409

### Обновить расписание СМРЛП [PUT]

+ Request (application/json)

        {
            "count": 2,
            "items": 
            [
                {
                    "id": 0,
                    "program_id": "b8e8bf60-25d9-11e8-a0e9-1c1b0d7db1e3",
                    "date": "12:30:46"
                },
                {
                    "id": 1,
                    "program_id": "b8e8bf60-25d9-21e8-a0e9-1c1b0d7db1e3",
                    "date": "12:50:46"
                }
            ]
        }

+ Response 200 (application/json)

+ Response 422

        {
            "count": 2,
            "items": 
            [
                {
                    "id": 0,
                    "program_id": "Указанная программа не найдена.",
                    "date": "17:30:46"
                },
                {
                    "id": 1,
                    "program_id": 2,
                    "date": "Чоо-то не так с этим временем"
                }
            ]
        }

+ Response 409

+ Response 404

## Включить работу СМРЛП по расписанию [/station/{id}/schedule/start]

Запуск работы СМРЛП по предварительно заданному расписанию

+ Parameters
    + id (number) - ID СМРЛП

### Включить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Остановить работу СМРЛП по расписанию [/station/{id}/schedule/stop]

Отмена работы СМРЛП по заданному расписанию и перевод РЛС в режим "ГОТОВНОСТЬ"

+ Parameters
    + id (number) - ID СМРЛП

### Остановить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404


## Запустить запись карты местных отражений [/station/{id}/local_reflection_map/start{?cycle}]

Запуск построения карты местных отражений. Ожидание ответа от СМРЛП не происходит,
всегда возвращается 200 OK

+ Parameters
    + id (number) - ID СМРЛП
    * cycle - количество циклов, в текущей итерации всегда 1

### Запись карты местных отражений [POST]

+ Response 200 (application/json)

## Остановить запись карты местных отражений [/station/{id}/local_reflection_map/stop]

Отмена запущенного процесса записи карты местных отражений. Ожидание ответа от СМРЛП не происходит,
всегда возвращается 200 OK

+ Parameters
    + id (number) - ID станции
    
### Остановить запись карты местных отражений [POST]

+ Response 200 (application/json)

## Запустить работу СМРЛП по программе [/station/{id}/program/{program_id}/start]

Запуск работы СМРЛП по указанной программе

+ Parameters
    + id (number) - ID СМРЛП
    + program_id (number) - ID программы

### Запустить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Остановить работу СМРЛП по программе [/station/{id}/program/stop]

Отмена работы СМРЛП по текущей программе и перевод РЛС в режим "ГОТОВНОСТЬ"
Примечание: для отмены работы по расписанию используется другой метод

+ Parameters
    + id (number) - ID СМРЛП

### Остановить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Запуск программы "КОНТРОЛЬ" для РЛС СМРЛП [/station/{id}/check/start]

Запуск встроенного контроля РЛС (особая программа)

+ Parameters
    + id (number) - ID СМРЛП

### Запустить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Данные метео [/station/{id}/nams_data{?date}]

Получение данных от метедатчиков СМРЛП (сортированные)

humidity(влажность) - %
pressure(давление) - мм.рт.с
wind_azimuth(направление ветра) - градусы
wind_speed(скорость ветра) - м/c
temp(температура) - градусы Цельсия

+ Parameters
    + id (number) - ID СМРЛП
    * date - Дата запроса данных (если не указана, то возвращается последние метеоданные)

### Получить [GET]

+ Response 200 (application/json)

        {
            "date": "2018-01-30T23:59:55+00:00",
            "humidity": "0",
            "pressure": "95120",
            "wind_azimuth": "29",
            "wind_speed": "2",
            "temp": "-34.5"
        }

## Получение данных метеостатистики [/station/{id}/meteo_stat{?date}]

Получение данных метеостатистики для обзоров (сортированные)

velocityMOAbs(скорость перемещения облачных облазований) - м/с
velocityMOAz(направление перемещения облачных облазований) - градусы
altitudeMaxMO(максимальная верхняя граница облачности) - км
altitudeMinRefl(минимальная нижняя граница радиоэха) - км
max_wp_id(максимальное МЯ) - идентификатор из списка

+ Parameters
    + id (number) - ID СМРЛП
    * date - Дата запроса данных (если не указана, то возвращается последняя метеостатистика)

### Получить [GET]

+ Response 200 (application/json)

        {
            "velocityMOAbs": 25,
            "velocityMOAz": 110,
            "altitudeMaxMO": 5600,
            "altitudeMinRefl": 700,
            "max_wp_id": 1,
            "date": "2018-01-30T17:25:52+00:00"
        }

## Список архивных обзоров [/station/{id}/archive_product_list]

Общий для РЛП и КС (сортированный)

+ Parameters
    + id (number) - ID радара

### Получить [GET]

+ Response 200 (application/json)

        {
            "count": 52,
            "items": [
                {"date": "2018-01-30T17:25:52"},
                {"date": "2018-01-30T17:30:46"},
                {"date": "2018-01-30T17:35:49"},
                {"date": "2018-01-30T17:40:54"},
                {"date": "2018-01-30T17:45:58"},
                {"date": "2018-01-30T17:51:01"},
                {"date": "2018-01-30T17:56:02"},
                {"date": "2018-01-31T17:25:02"},
                {"date": "2018-01-31T17:30:02"},
                {"date": "2018-01-31T17:45:20"},
                {"date": "2018-02-01T12:05:26"},
                {"date": "2018-02-01T15:05:51"},
                {"date": "2018-02-02T19:30:51"},
                {"date": "2018-02-02T21:16:10"},
                {"date": "2018-02-02T23:05:51"},
                {"date": "2018-02-03T15:06:51"},
                {"date": "2018-02-03T16:07:51"},
                {"date": "2018-02-04T17:08:51"},
                {"date": "2018-02-04T18:09:51"},
                {"date": "2018-02-04T19:10:51"},
                {"date": "2018-02-04T20:11:51"},
                {"date": "2018-02-05T01:12:51"},
                {"date": "2018-02-05T02:13:51"},
                {"date": "2018-02-05T03:14:51"},
                {"date": "2018-02-05T04:15:51"},
                {"date": "2018-02-06T02:16:51"},
                {"date": "2018-02-06T03:17:51"},
                {"date": "2018-02-06T04:18:51"},
                {"date": "2018-02-06T05:19:51"},
                {"date": "2018-02-06T05:25:51"},
                {"date": "2018-02-07T07:21:51"},
                {"date": "2018-02-07T08:22:51"},
                {"date": "2018-02-07T09:23:51"},
                {"date": "2018-02-07T10:24:51"},
                {"date": "2018-02-08T11:25:51"},
                {"date": "2018-02-08T12:26:51"},
                {"date": "2018-02-08T13:27:51"},
                {"date": "2018-02-09T14:28:51"},
                {"date": "2018-02-10T15:29:51"},
                {"date": "2018-02-10T16:30:51"},
                {"date": "2018-02-11T17:31:51"},
                {"date": "2018-02-11T18:32:51"},
                {"date": "2018-02-12T19:33:51"},
                {"date": "2018-02-12T20:34:51"},
                {"date": "2018-02-13T21:35:51"},
                {"date": "2018-02-13T22:36:51"},
                {"date": "2018-02-13T23:37:51"},
                {"date": "2018-02-14T01:38:51"},
                {"date": "2018-02-14T02:39:51"},
                {"date": "2018-02-15T03:40:51"},
                {"date": "2018-02-15T14:41:51"},
                {"date": "2018-02-16T15:42:51"}
            ]
        }

## Получение карт РЛП [/station/{id}/rlp/{type}/{?rlp_id}{?only_dangerous}{?altitude}{?date}{?cell_size}{?radius}]

Получение карт РЛП для обзоров (сортированные)

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + type (str) - тип данных, для данной итерации всегда png
    * rlp_id - id радиолокационного продукта
    * only_dangerous - отображать только ОМЯ [True/False]
    * altitude - Высота в метрах [100:20000]
    * date - Дата обзора (если не указан, то возвращается последнее РЛП)
    * cell_size - Размер области, которую покрывает 1 пиксель в м., в текущей итерации всегда 1000
    * radius - Радиус обзора в км., в текущей итерации всегда 100

+ Response 200 (application/json)

        {
            "date": "2017-12-28T08:00:49+00:00", 
            "type": "png", 
            "params": {"radius": 100, "cell_size": 1000, "image_size": 209},
            "url": "/wpcell.png"
        }

## Получение высот для некоторых РЛП [/station/{id}/rlp_altitudes{?date}]
От 0.1 до 20.0

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    * date - Дата обзора

+ Response 200 (application/json)

        [
            0.1, 
            0.3, 
            0.6, 
            1.0, 
            1.5,
            2.0,
            2.2,
            2.4,
            2.6,
            2.8,
            3.0,
            3.2,
            3.4,
            3.6,
            3.8
        ]

+ Response 404

## Получение высот для КС [/station/{id}/cs_altitudes{?date}]
От 0.1 до 20.0

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    * date - Дата обзора

+ Response 200 (application/json)

        [
            0.1, 
            0.2, 
            0.3, 
            0.4, 
            0.5, 
            0.6, 
            0.7, 
            0.8, 
            0.9, 
            1.0, 
            1.1, 
            1.2,
            1.3,
            1.4,
            1.5,
            1.6,
            1.7,
            1.8,
            1.9,
            2.0,
            2.1
        ]

+ Response 404

## Получение КС [/station/{id}/cs/{type}/{?cs_id}{?indicator}{?altitude}{?date}{?cell_size}{?radius}{?angle}]

Получение конических сечений для обзоров (сортированные)

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + type (str) - тип данных, для данной итерации всегда png
    * cs_id - тип конического сечения 
    * indicator -  CAPPI / PPI / MAXCAPPI
    * altitude - Высота в метрах (только для CAPPI) [100:20000]
    * date - Дата обзора (если не указан, то возвращается последнее КС)
    * cell_size - Размер области, которую покрывает 1 пиксель в м., в текущей итерации всегда 1000
    * radius - Радиус обзора в км., в текущей итерации всегда 100
    * angle (number) - Угол места (градусы) (только для PPI) [0.0:90.0]
    

+ Response 200 (application/json)

        {
            "date": "2018-01-30T17:25:52+00:00",
            "type": "png",
            "params": {"radius": 100, "cell_size": 1000, "image_size": 200},
            "url": "/rlp/0/?img=monocle-autodor-node-001_2018-01-30_17-25-52_cs-dbz-cappi-100-120-1000.png"
        }

+ Response 404

## Получение углов места [/station/{id}/angles_array{?date}]

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    * date - Дата обзора

+ Response 200 (application/json)

        [
            0,
            0.791015625,
            1.58203125,
            2.373046875,
            3.1640625,
            4.04296875,
            4.833984375,
            5.625,
            6.416015625,
            7.20703125,
            7.998046875,
            8.7890625,
            9.580078125,
            10.37109375,
            12.392578125,
            14.4140625,
            16.34765625,
            34.453125,
            37.44140625,
            40.4296875,
            43.41796875,
            46.40625,
            49.39453125
        ]

+ Response 404

## Метеоинформация в указанной точке [/station/{id}/{product_type}/point/{?latitude}{?longitude}]

Получение данных маркера для указанного продукта. 
distance, x, z - в километрах

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + product_type - РЛП или КС
    * latitude - Координаты точки
    

+ Response 200 (application/json)

        {
            "azimuth": 331,
            "distance": 26.4, 
            "x": -6.3,
            "z": 18,
            "rlp_data": [
                {
                    "id": 1,
                    "title": "Метеоявления",
                    "items": [
                        {
                            "id": 1,
                            "title": null,
                            "value": "Ливень слабый",
                            "units": null
                        }
                    ]
                },
                {
                    "id": 2,
                    "title": "Векторное поле скоростей",
                    "items": [
                        {
                            "id": 1,
                            "title": "Высота",
                            "value": 4.5,
                            "units": "км"
                        },
                        {
                            "id": 2,
                            "title": "Скорость",
                            "value": 26.1,
                            "units": "м/с"
                        }
                    ]
                }
            ]
        }
            
## Программы [/program/list{?mode}{?title}{?limit}{?offset}]

Работа по списком программ (для всей АС СМРЛП)

### Получить список программ [GET]

+ Parameters
    * mode - Фильтр режима
    * title - Фильтр по названию
    * limit - Количество строк на странице
    * offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 2,
            "items": [
                {
                    "id": "b8e8bf60-25d9-11e8-a0e9-1c1b0d7db1e3",
                    "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
                    "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
                    "_comment_program": "Массив позиций по УМ",
                    "program": {
                        "angles_array": [
                            0,
                            0.791015625,
                            1.58203125,
                            2.373046875,
                            3.1640625,
                            4.04296875,
                            4.833984375,
                            5.625,
                            6.416015625,
                            7.20703125,
                            7.998046875,
                            8.7890625,
                            9.580078125,
                            10.37109375,
                            12.392578125,
                            14.4140625,
                            16.34765625,
                            34.453125,
                            37.44140625,
                            40.4296875,
                            43.41796875,
                            46.40625,
                            49.39453125
                        ],
                        "_comment_av_azimuth_change": "Azimuth at which the change of angle in the vertical",
                        "av_azimuth_change": 0,
                        "_comment_azimuth_scan_speed": "Speed scanning in azimuth",
                        "azimuth_scan_speed": 23.820384889522455,
                        "_comment_blank_sectors_array": "Массив секторов блокировки",
                        "blank_sectors_array": [
                            {
                              "start": 18.369140625,
                              "end": 20.390625
                            },
                            {
                              "start": 22.412109375,
                              "end": 22.412109375
                            },
                            {
                              "start": 25.400390625,
                              "end": 28.388671875
                            }
                        ],
                        "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                        "mode": 5,
                        "_comment_raster_left_azimuth": "left border of a raster review",
                        "raster_left_azimuth": 15.029296875,
                        "_comment_raster_right_azimuth": "right border of a raster review",
                        "raster_right_azimuth": 74.970703125,
                        "_comment_scope_range": "Current scope range",
                        "scope_range": 50,
                        "duration": "00:10:00"
                    }
                },
                {
                    "id": "b8e8bf60-25d9-21e8-a0e9-1c1b0d7db1e3",
                    "description": "Cканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 100 км",
                    "name": "СЕКТОР 100 км УМ 0-50° Аз45° шир. 60°",
                    "_comment_program": "Массив позиций по УМ",
                    "program": {
                        "angles_array": [
                            0,
                            0.791015625,
                            1.58203125,
                            2.373046875,
                            3.1640625,
                            4.04296875,
                            4.833984375,
                            5.625,
                            6.416015625,
                            7.20703125,
                            7.998046875,
                            8.7890625,
                            9.580078125,
                            10.37109375,
                            12.392578125,
                            14.4140625,
                            16.34765625,
                            34.453125,
                            37.44140625,
                            40.4296875,
                            43.41796875,
                            46.40625,
                            49.39453125
                        ],
                        "_comment_av_azimuth_change": "Azimuth at which the change of angle in the vertical",
                        "av_azimuth_change": 0,
                        "_comment_azimuth_scan_speed": "Speed scanning in azimuth",
                        "azimuth_scan_speed": 23.820384889522455,
                        "_comment_blank_sectors_array": "Массив секторов блокировки",
                        "blank_sectors_array": [
                            {
                              "start": 18.369140625,
                              "end": 20.390625
                            },
                            {
                              "start": 22.412109375,
                              "end": 22.412109375
                            },
                            {
                              "start": 25.400390625,
                              "end": 28.388671875
                            }
                        ],
                        "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                        "mode": 5,
                        "_comment_raster_left_azimuth": "left border of a raster review",
                        "raster_left_azimuth": 15.029296875,
                        "_comment_raster_right_azimuth": "right border of a raster review",
                        "raster_right_azimuth": 74.970703125,
                        "_comment_scope_range": "Current scope range",
                        "scope_range": 50,
                        "duration": "00:10:00"
                    }
                }
            ]
        }
        
## Программа [/program/{id}]

Работа с заданной программой (для всей АС СМРЛП)

+ Parameters
    + id (number) - ID программы

### Получить [GET]

+ Response 200 (application/json)

        {
            "id": "b8e8bf60-25d9-11e8-a0e9-1c1b0d7db1e3",
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "angles_array": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_av_azimuth_change": "Azimuth at which the change of angle in the vertical",
                "av_azimuth_change": 0,
                "_comment_azimuth_scan_speed": "Speed scanning in azimuth",
                "azimuth_scan_speed": 23.820384889522455,
                "_comment_blank_sectors_array": "Массив секторов блокировки",
                "blank_sectors_array": [
                    {
                      "start": 18.369140625,
                      "end": 20.390625
                    },
                    {
                      "start": 22.412109375,
                      "end": 22.412109375
                    },
                    {
                      "start": 25.400390625,
                      "end": 28.388671875
                    }
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_raster_left_azimuth": "left border of a raster review",
                "raster_left_azimuth": 15.029296875,
                "_comment_raster_right_azimuth": "right border of a raster review",
                "raster_right_azimuth": 74.970703125,
                "_comment_scope_range": "Current scope range",
                "scope_range": 50,
                "duration": "00:10:00"
            }
        }

+ Response 404

### Удалить программу [DELETE]

+ Response 204

+ Response 409

        {
            "count": 2,
            "station_ids": [1,4]
        }
    
+ Response 404

### Создать программу [POST /program]

+ Request (application/json)

        {
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "program": {
                "_comment_angles_array": "Массив позиций по УМ",
                "angles_array": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_av_azimuth_change": "Azimuth at which the change of angle in the vertical",
                "av_azimuth_change": 0,
                "_comment_azimuth_scan_speed": "Speed scanning in azimuth",
                "azimuth_scan_speed": 23.820384889522455,
                "_comment_blank_sectors_array": "Массив секторов блокировки",
                "blank_sectors_array": [
                    {
                      "start": 18.369140625,
                      "end": 20.390625
                    },
                    {
                      "start": 22.412109375,
                      "end": 22.412109375
                    },
                    {
                      "start": 25.400390625,
                      "end": 28.388671875
                    }
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_raster_left_azimuth": "left border of a raster review",
                "raster_left_azimuth": 15.029296875,
                "_comment_raster_right_azimuth": "right border of a raster review",
                "raster_right_azimuth": 74.970703125,
                "_comment_scope_range": "Current scope range",
                "scope_range": 50,
                "duration": "00:10:00"
            }
        }

+ Response 422 (application/json)

    + Body

            {
                "program": {
                    "angles_array": "Присутствуют невалидные значения",
                    "av_azimuth_change": "Невалидное значение",
                    "azimuth_scan_speed": "Невалидное значение",
                    "blank_sectors_array": "Присутствуют невалидные значения",
                    "mode": "Невалидное значение",
                    "raster_left_azimuth": "Невалидное значение",
                    "raster_right_azimuth": "Невалидное значение",
                    "scope_range": "Невалидное значение",
                    "duration": "Невалидное значение"
                }
            }

+ Response 201 (application/json)

### Обновить программу [PUT]

+ Request (application/json)

        {
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "program": {
                "_comment_angles_array": "Массив позиций по УМ",
                "angles_array": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_av_azimuth_change": "Azimuth at which the change of angle in the vertical",
                "av_azimuth_change": 0,
                "_comment_azimuth_scan_speed": "Speed scanning in azimuth",
                "azimuth_scan_speed": 23.820384889522455,
                "_comment_blank_sectors_array": "Массив секторов блокировки",
                "blank_sectors_array": [
                    {
                      "start": 18.369140625,
                      "end": 20.390625
                    },
                    {
                      "start": 22.412109375,
                      "end": 22.412109375
                    },
                    {
                      "start": 25.400390625,
                      "end": 28.388671875
                    }
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_raster_left_azimuth": "left border of a raster review",
                "raster_left_azimuth": 15.029296875,
                "_comment_raster_right_azimuth": "right border of a raster review",
                "raster_right_azimuth": 74.970703125,
                "_comment_scope_range": "Current scope range",
                "scope_range": 50,
                "duration": "00:10:00"
            }
        }

+ Response 200 (application/json)

+ Response 422 (application/json)

    + Body

            {
                "program": {
                    "angles_array": "Присутствуют невалидные значения",
                    "av_azimuth_change": "Невалидное значение",
                    "azimuth_scan_speed": "Невалидное значение",
                    "blank_sectors_array": "Присутствуют невалидные значения",
                    "mode": "Невалидное значение",
                    "raster_left_azimuth": "Невалидное значение",
                    "raster_right_azimuth": "Невалидное значение",
                    "scope_range": "Невалидное значение",
                    "duration": "Невалидное значение"
                }
            }

+ Response 409

        {
            "count": 2,
            "station_ids": [1,4]
        }

+ Response 404    

## Журнал событий [/station_log/list{?type}{?station}{?from}{?to}{?message}{?limit}{?offset}]

Получение журнала событий заданного СМРЛП

### Получить список событий [GET]

+ Parameters
    * type - Тип события, информация или ошибка (error|info)
    * station - id СМРЛП
    * from - Начальный период поиска
    * to - Конечный период поиска
    * message - Сообщение
    * limit - Количество строк на странице
    * offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 4,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Превышен период обновления параметров калибровки."
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "error",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        },
                        "message": "Ошибка подключения к МРЛС. Проверьте настройки."
                    },
                    {
                        "id": 3,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Карта местных отражений очищена"
                    },
                    {
                        "id": 4,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 2,
                            "title": "Чкаловский"
                        },
                        "message": "Карта местных отражений очищена"
                    }
                ]
        }
        
## Уведомления [/alarm/list{?stations}]

Глобальный список уведомлений

### Получить список уведомлений [GET]

+ Parameters
    * stations - список id СМРЛП


+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "error",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Ошибка соединения."
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        },
                        "message": "Слабый сигнал."
                    }
                ]
        }
        
## Опасные явления [/dangerous_meteo/list{?stations}]

Голобальный список обнаруденных опасных метеоявлений

### Получить список опасных явлений [GET]

+ Parameters
    * stations - список id СМРЛП


+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "Шторм",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        }
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "Сильный ливень",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        }
                    }
                ]
        }

## Настройки экспорта BUFR [/settings/bufr]
 
Экспорт данных АС СМРЛП в заданные направления по протоколу FTP
 
### Получить список настроек экспорта BUFR [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "active_mode": true,
                        "path": "/var/lib/monocle/data/",
                        "login": "login",
                        "password": "password",
                        "stations": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "active_mode": false,
                        "path": "/var/lib/monocle/data/",
                        "login": "login",
                        "password": "password",
                        "stations": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }

### Обновить список настроек экспорта BUFR [PUT]

+ Request (application/json)

        [
            {
                "active": true,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "login": "login",
                "password": "password",
                "stations": [
                    {
                        "id": 1,
                        "title": "Орловка"
                    },
                    {
                        "id": 2,
                        "title": "Чкаловский"
                    },
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            },
            {
                "active": false,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "login": "login",
                "password": "password",
                "stations": [
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            }
        ]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "login": "login",
                        "password": "password", 
                        "stations": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "login": "login",
                        "password": "password", 
                        "stations": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }
    
+ Response 422 (application/json)

        {
            "count": 1,
            "items": 
                [
                    {
                        "index": 1,
                        "active": "Невалидное значение",
                        "ip": "Невалидное значение",
                        "port": "Невалидное значение",
                        "path": "Невалидное значение",
                        "stations": "Невалидное значение"
                    }
                ]
        }

## Построение карт РЛП [/settings/productrender]
 
Настройки алгоритма построения карт РЛП

### Получить настройки для построения карт РЛП [GET]

+ Response 200 (application/json)

        { 
            "_comment_vector_velocity_field": "",
            "vector_velocity_field": {
                "_comment_circular_horizontal_pitch": "Шаг по горизонтали в режиме ОБЗОР",
                "circular_horizontal_pitch": 8000, 
                "_comment_circular_vertical_pitch": "Шаг по вертикали в режиме ОБЗОР",
                "circular_vertical_pitch": 1000, 
                "_comment_sector_horizontal_pitch": "Шаг по горизонтали в режиме СЕКТОР",
                "sector_horizontal_pitch": 8000, 
                "_comment_sector_vertical_pitch": "Шаг по вертикали в режиме СЕКТОР",
                "sector_vertical_pitch": 1000,
                "_comment_vector_size": "Размер ячейки вектора поля скоростей",
                "vector_size": 5,
                "_comment_vector_thickness": "Толщина линии вектора поля скоростей",
                "vector_thickness": 3
            }, 
            "_comment_wind_shear_field": "Поля сдвигов ветра",
            "wind_shear_field": { 
                "_comment_circular_max_altitude": "Максимальная высота в режиме ОБЗОР",
                "circular_max_altitude": 100, 
                "_comment_circular_max_range": "Максимальная дальность в режиме ОБЗОР",
                "circular_max_range": 100, 
                "_comment_sector_max_altitude": "Максимальная высота в режиме СЕКТОР",
                "sector_max_altitude": 100, 
                "_comment_sector_max_range": "Максимальная дальность в режиме СЕКТОР",
                "sector_max_range": 100, 
                "_comment_horizontal_pitch": "Шаг по вертикали",
                "horizontal_pitch": 100, 
                "_comment_vertical_pitch": "Шаг по горизонтали",
                "vertical_pitch": 100 
            }, 
            "_comment_weather_map": "Карты МЯ ",
            "weather_map": {
                "_comment_cell_size": "Размер ячейки МЯ, м",
                "cell_size": 1000, 
                "_comment_contour_line_generalization": "Степень генерализации контуров МЯ",
                "contour_line_generalization": 3, 
                "_comment_contour_line_expansion": "Величины расширения контуров МЯ",
                "contour_line_expansion": 3
            },
            "_comment_vertical_section": "Вертикальное сечение",
            "vertical_section": { 
                "horizontal_pitch": 100, 
                "vertical_pitch": 100 
            }, 
            "_comment_accumulated_precipitation": "Размера ячейки карты накопленных осадков",
            "accumulated_precipitation": { 
                "cell_size": 100 
            },
            "_comment_vertically_integrated_liquid": "Размер ячейки построения карты вертикально интегрированной водности",
            "vertically_integrated_liquid": { 
                "cell_size": 100
            }
        }

### Обновить настройки для построения карт [PUT]

+ Request (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": 8000, 
                "circular_vertical_pitch": 1000, 
                "sector_horizontal_pitch": 8000, 
                "sector_vertical_pitch": 1000,
                "vector_size": 5,
                "vector_thickness": 3
            },
            "wind_shear_field": { 
                "circular_max_altitude": 100, 
                "circular_max_range": 100, 
                "sector_max_altitude": 100, 
                "sector_max_range": 100, 
                "horizontal_pitch": 100, 
                "vertical_pitch": 100 
            },
            "weather_map": {
                "cell_size": 1000, 
                "contour_line_generalization": 3, 
                "contour_line_expansion": 3
            },
            "vertical_section": { 
                "horizontal_pitch": 100, 
                "vertical_pitch": 100 
            },
            "accumulated_precipitation": { 
                "cell_size": 100 
            },
            "vertically_integrated_liquid": { 
                "cell_size": 100
            }
        }

+ Response 200 (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": 8000, 
                "circular_vertical_pitch": 1000, 
                "sector_horizontal_pitch": 8000, 
                "sector_vertical_pitch": 1000,
                "vector_size": 5,
                "vector_thickness": 3
            },
            "wind_shear_field": { 
                "circular_max_altitude": 100, 
                "circular_max_range": 100, 
                "sector_max_altitude": 100, 
                "sector_max_range": 100, 
                "horizontal_pitch": 100, 
                "vertical_pitch": 100 
            },
            "weather_map": {
                "cell_size": 1000, 
                "contour_line_generalization": 3, 
                "contour_line_expansion": 3
            },
            "vertical_section": { 
                "horizontal_pitch": 100, 
                "vertical_pitch": 100 
            },
            "accumulated_precipitation": { 
                "cell_size": 100 
            },
            "vertically_integrated_liquid": { 
                "cell_size": 100
            }
        }

+ Response 422 (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": "Невалидное значение",
                "circular_vertical_pitch": "Невалидное значение",
                "sector_horizontal_pitch": "Невалидное значение",
                "sector_vertical_pitch": "Невалидное значение",
            },
            "wind_shear_field": {
                "sector_max_range": "Невалидное значение"
            },
            "vertically_integrated_liquid": {
                "cell_size": "Невалидное значение"
            }
        }

## Список настроек цветовых шкал [/settings/color_scale/list]

Цветовые шкалы - легенды при выводе продуктов

### Получить список настроек цветовых шкал [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items":
            [
                {
                    "id": 0,
                    "title": "Отражаемость",
                    "count": 3,
                    "items":
                    [
                        {
                            "index": 0,
                            "value": 30,
                            "color": "#010178"
                        },
                        {
                            "index": 1,
                            "value": 35,
                            "color": "#fffb00"
                        },
                        {
                            "index": 2,
                            "value": 40,
                            "color": "#f500f6"
                        }
                    ]
                },
                {
                    "id": 1,
                    "title": "Радиальная скорость",
                    "count": 3,
                    "items":
                    [
                        {
                            "index": 0,
                            "value": 30,
                            "color": "#010178"
                        },
                        {
                            "index": 1,
                            "value": 35,
                            "color": "#fffb00"
                        },
                        {
                            "index": 2,
                            "value": 45,
                            "color": "#f500f6"
                        }
                    ]
                }
            ]        
        }

## Настройки цветовой шкалы [/settings/color_scale/{id}]

Редактирование цветовых шкал

+ Parameters
    + id (number) - ID раздела настроек цветовой шкалы

### Обновить настройки цветовой шкалы [PUT]

+ Request (application/json)


        [
            {
                "index": 1,
                "value": 30,
                "color": "#010178"
            },
            {
                "index": 2,
                "value": 35,
                "color": "#fffb00"
            },
            {
                "index": 3,
                "value": 40,
                "color": "#f500f6"
            }
        ]

+ Response 200 (application/json)


        [
            {
                "index": 1,
                "value": 30,
                "color": "#010178"
            },
            {
                "index": 2,
                "value": 35,
                "color": "#fffb00"
            },
            {
                "index": 3,
                "value": 40,
                "color": "#f500f6"
            }
        ]
        
+ Response 422 (application/json)


        [
            {
                "index": 1,
                "value": "Невалидное значение",
                "color": "Невалидное значение"
            }
        ]
        
+ Response 404

## Настройки цветовой шкалы по умолчанию [/settings/color_scale/{id}/default]

Всегда может понадобиться сбросить цветовую шкалу в состояние "по-умолчанию"

+ Parameters
    + id (number) - ID раздела настроек цветовой шкалы

### Получить настройки цветовой шкалы по умолчанию [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "count": 3,
            "title": "Радиальная скорость",
            "items":
            [
                {
                    "id": 0,
                    "value": 30,
                    "color": "#010178"
                },
                {
                    "id": 1,
                    "value": 35,
                    "color": "#fffb00"
                },
                {
                    "id": 2,
                    "value": 40,
                    "color": "#f500f6"
                }
            ]
        }
        

## Критерии классификации типов метеоявлений по умолчанию [/settings/default_weather_criteria]

Типовой (зашитый производителем) перечень критериев классификации МЯ по фиксированному перечню параметров
Для редкатирования см. настроки отдельного СМРЛП - для каждого СМРЛП теоретически могут быть свои критерии

### Получить [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items":
            [
                {
                    "id": 0, 
                    "type": "Облачность (слоистообразная облачность)",
                    "count": 1,
                    "items":
                    [
                    {
                        "index": 0,
                        "code": "Cl_dBZ23_min",
                        "title": "Минимальное значение радиолокационной отражаемости на уровнях Z2 и Z3",
                        "measurement_unit": "dBZ",
                        "warm": 10,
                        "cold": -10, 
                        "service_life": "All"
                    }
                    ]
                },
                {
                    "id": 1, 
                    "type": "Облачность (кучевая облачность)",
                    "count": 1,
                    "items":
                    [
                    {
                        "index": 0,
                        "code": "Cl_dBZ2_min",
                        "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                        "measurement_unit": "dBZ",
                        "service_life": "All"
                    },
                    {
                        "index": 1,
                        "code": "Cl_dBZ3_min",
                        "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                        "measurement_unit": "dBZ",
                        "warm": 35,
                        "cold": 30,
                        "service_life": "All"
                    }
                    ]
                }
            ]
        }

## Поправка на север [/north_azimuth/{id}]

Получение и изменение текущей заданной на МРЛС поправки на север (нулевого азимута)
Изменение происходит с заданием расстояний до ориентиров

+ Parameters
    + id (number) - ID СМРЛП

### Получить [GET]

+ Response 200 (application/json)

        {
            "_comment_center_azimuth": "Установленное в МРЛС значение нулевого азимута, град.",
            "center_azimuth": 12.5
        }

+ Response 404

### Установить [POST]

+ Request (application/json)

        {
            "_comment_dist_to_north": "Расстояние до ориентира на Север, м",
            "dist_to_north": 200.0,
            "_comment_dist_to_install": "Расстояние до ориентира установки, м",
            "dist_to_install": 300.3,
            "_comment_dist_north_install": "Расстояние между ориентиром на Север и ориентиром установки, м",
            "dist_north_install": 100.0,
            "_comment_install_at_west": "Положение ориентира установки относительно антенны (true - западнее, false - восточнее)",
            "install_at_west": true
        }

+ Response 200

+ Response 422 (application/json)

        {
            "dist_to_north": "Невалидное значение",
            "dist_to_install": "Невалидное значение",
            "dist_north_install": "Невалидное значение",
            "install_at_west": "Невалидное значение"
        }

## Вертикальное сечение [/vertical_section_by_route]

Предоставление вертикального сечения по маршруту для выбранного метеопродукта на заданном диапазоне высот.

### Получить [POST]

+ Request  (application/json)

        {
            "station_id": 1,
            "date": "2017-05-15T08:30:00",
            "route_points": [{
                "latitude": 55.807775,
                "longitude": 37.566814
            },
            {
                "latitude": 55.807775,
                "longitude": 37.566814
            }],
            "max_altitude": 5000.2,
            "rlp_type": 2
        }

+ Response 200

## Вертикальный профиль [/vertical_profile]

Предоставление вертикального профиля для выбранного метеопродукта на заданном диапазоне  высот

### Получить [POST]

+ Request  (application/json)

        {
            "station_id": 1,
            "date": "2017-05-15T08:30:00",
            "marker_pos": {
                "latitude": 55.807775,
                "longitude": 37.566814
            },
            "max_altitude": 5000.2,
            "cs_type": 2
        }

+ Response 200 (application/json)

        {
            "heights": [
                0,
                100,
                200,
                300,
                400,
                500,
                600,
                700,
                800,
                900,
                1000,
                1100,
                1200,
                1300,
                1400
                ],
            "value": 0,
            "values": [
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10,
                -10
                ]
        }

## Текущие значения параметров работы МРЛС [/station/{id}/mrls_status]

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП

+ Response 200 (application/json)

        {
            "packet_number": {
                "title": "Номер пакета",
                "value": "Нет данных"
            },
            "mode": {
                "title": "Режим работы МРЛС",
                "value": "Нет данных"
            },
            "scale_base": {
                "title": "База масштаба по Д, км",
                "value": "Нет данных"
            },
            "countdowns": {
                "title": "Отсчетов по Д",
                "value": "Нет данных"
            },
            "discrete_size": {
                "title": "Размер дискр. Д, м",
                "value": "Нет данных"
            },
            "radiation": {
                "title": "ПРД: изл. СВЧ",
                "value": "Нет данных"
            },
            "info": {
                "title": "Инф. МРЛС",
                "value": "Нет данных"
            },
            "state": {
                "title": "Общ. состояние МРЛС",
                "value": "Нет данных"
            },
            "antenna_state": {
                "title": "Исправность Ант.",
                "value": "Нет данных"
            },
            "ppm_state": {
                "title": "Исправность ППМ",
                "value": "Нет данных"
            },
            "antenna_az": {
                "title": "Прив. Аз Ант.",
                "value": "Нет данных"
            },
            "antenna_ea": {
                "title": "Прив. УМ Ант.",
                "value": "Нет данных"
            },
            "ppm_dsp": {
                "title": "ППМ: модуль DSP",
                "value": "Нет данных"
            },
            "ppm_sharu": {
                "title": "ППМ: рег. ШАРУ",
                "value": "Нет данных"
            },
            "ppm_prm": {
                "title": "ППМ: ПРМ",
                "value": "Нет данных"
            },
            "state_channel": {
                "title": "Исправлность канала упр.",
                "value": "Нет данных"
            },
            "control": {
                "title": "КОНТРОЛЬ",
                "value": "Нет данных"
            },
            "tubler_az": {
                "title": "Тублер привода азимута",
                "value": "Нет данных"
            },
            "tubler_ea": {
                "title": "Тублер привода УМ",
                "value": "Нет данных"
            },
            "az": {
                "title": "Азимут, град",
                "value": "Нет данных"
            },
            "ea": {
                "title": "Угол Места, град",
                "value": "Нет данных"
            },
            "ea_posititon": {
                "title": "Позиция в программе УМ заданный, град",
                "value": "Нет данных"
            },
            "az_ea": {
                "title": "Аз смены УМ, град",
                "value": "Нет данных"
            },
            "az_right": {
                "title": "Правый азимут в режиме СЕКТОР, град",
                "value": "Нет данных"
            },
            "az_left": {
                "title": "Левый азимут в режиме СЕКТОР, град",
                "value": "Нет данных"
            },
            "speed": {
                "title": "Угловая скорость Г, град/c",
                "value": "Нет данных"
            },
            "ea_position_count": {
                "title": "Число позиций УМ",
                "value": "Нет данных"
            },
            "bs_position_count": {
                "title": "Число позиций секторов блокировки",
                "value": "Нет данных"
            }
        }

## Каналы излучения [/settings/{id}/channels]

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП

+ Response 200 (application/json)

        [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12
        ]

## Список уведомлений об опасных метеоявлениях [/station/{id}/dangerous_meteo_list]

Список обнаруженных опасных явлений за последний час

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП

+ Response 200 (application/json)

        {
            "count": 3,
            "items": [
                {
                    "date": "2017-05-15T08:39:00",
                    "max_wp_id": 15
                },
                {
                    "date": "2017-05-15T08:49:00",
                    "max_wp_id": 12
                },
                {
                    "date": "2017-05-15T08:59:00",
                    "max_wp_id": 8
                },
                {
                    "date": "2017-05-15T08:59:00",
                    "max_wp_id": 5
                }
            ]
        }

## Уведомления [/notification]

Поднимаем один вебсокет для общения с интерфейсом. В поле type указываем типа уведомления. Состав content'a зависит от типа

### Уведомление об окончании обработки очередного пакета данных

+ Request (application/json)

        {
            "type": "new_product",
            "content": {
                "station_id":0,
                "date": "2017-05-15T08:30:00",
                "max_wp_id": 15
            }
        }
        
### Уведомление об об отказе компонентов системы

+ Request (application/json)

        {
            "type": "failure_message",
            "content": {
                "station_id":0,
                "message": "Отказ метео локатора",
                "date": "2017-05-15T08:30:00"
            }
        }

### Уведомление о соcтоянии
Тут 4 статуса будет приходить одновременно:
 Статус исправности СМРЛП
 Актуальность изотермы
 Ведется запись местных отражений
 Ведется проверка работоспособности
И если потом пригодится:
 Статус связи
 Прогресс

+ Request (application/json)

        {
            "type": "state",
            "content": {
                "station_id": 4,
                "equipment_status": true,
                "_comment_isotherm_status": "true - актуальная изотерма, false - нет",
                "isotherm_status": true
                "local_reflections_status": false,
                "control_status": false,
                "exchange_status": true,
                "rotation_status": 60
            }
        }

### Уведомление об обновлении настроек

+ Request (application/json)

        {
            "type": "notification",
            "content": {
                "station_id": 4,
                "message": "Настройки СМРЛП Орловка успешно обновлены",
                "date": "2017-05-15T08:30:00"
            }
        }